name: AulaMind Curriculum Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  curriculum:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pymupdf

      - name: Convert PDFs to TXT
        run: |
          python pdf_a_txt.py

      - name: Normalize Curriculum
        run: |
          python normalizador_curricular.py

      - name: Commit generated curriculum
        run: |

          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"

          git add data/
          git add txt/

          git commit -m "🤖 Auto curriculum update" || echo "No changes"

          git push origin main
